### ISSUE TITLE
sort buttons are not displayed in the interfaces of various mods

### ISSUE THREAD

**Issue by teshich** [Chailotl/inventory-sort#1]
Minecraft version: 1.20.1
Fabric version: 0.15.9

**I noticed that in interfaces added by mods such as** 
Spectrum - https://modrinth.com/mod/spectrum (They haven't updated their page for a long time lol), 
Farmers Delight Refabricated - https://modrinth.com/mod/farmers-delight-refabricated, 
Modern Industrialization - https://modrinth.com/mod/modern-industrialization, 
Ad Astra - https://modrinth.com/mod/ad-astra, 
Applied Еnergisctics 2 - https://modrinth.com/mod/ae2, 
**are no sorting buttons.**

**Examples:**
![image](https://github.com/Chailotl/inventory-sort/assets/125819901/f8213154-c62c-48c3-ab25-0d56d791f9db)
![image](https://github.com/Chailotl/inventory-sort/assets/125819901/de29ba57-19e3-4c6d-b2e0-830f3f0ac945)
![image](https://github.com/Chailotl/inventory-sort/assets/125819901/6e546990-73ac-40cc-b056-c7384b85920f)
![image](https://github.com/Chailotl/inventory-sort/assets/125819901/556c53aa-359f-49fa-8cca-099ffed00b9c)
![image](https://github.com/Chailotl/inventory-sort/assets/125819901/91fa1635-8fd6-4c24-a0d5-bfb1585f3b21)

**_It seems to me that it would be enough to add only a button for sorting the player’s inventory, without adding the button for sorting the container from the mod and the buttons for transferring items to/from the inventory._**

**Comment by Chailotl** [comment]
In 1.1.0 inventory sort buttons should appear in most modded screens and container sort/transfer buttons should appear in most modded container screens, and in 1.2.0 config options were added to let you control this exactly so I'm closing this issue now.
