### ISSUE TITLE
Sorting is only sorting by count, no matter how many tags I add or remove from the config

### ISSUE THREAD

**Issue by beezzinha** [Chailotl/inventory-sort#13]
Example images.

This is how a chest full of items looks like before sorting. A mess.
![image](https://github.com/user-attachments/assets/3ff732c9-706b-45ed-866b-ab6b23b38577)

And this is how it looks like after sorting. Still a mess, but this time organized by stack ammount.
![image](https://github.com/user-attachments/assets/4b83df9f-e3bf-4a62-88a6-13f90b7a736e)

Also the blocks don't all group together, which is weird. For some reason the deepslate is in the middle of the cobblestone blocks.

**Comment by gameo7** [comment]
I've noticed this only happens on servers. Changing the config in client seems to work in singleplayer worlds

**Comment by beezzinha** [comment]
> I've noticed this only happens on servers. Changing the config in client seems to work in singleplayer worlds

Except this happened in a singleplayer word for me. How do I change the config in client? I've only been editting the config file

**Comment by gameo7** [comment]
For me I was able to edit the config just fine through modmenu. You can't actually sort the order entries (i don't know if this changes priority), but you can add them to the bottom or edit the other entries.

My version was on 1.20.1 and the screenshot was taken from 1.20.4.

![2024-07-31_12 09 34](https://github.com/user-attachments/assets/7b236c32-e0a1-4bed-b394-135b4de82193)

**Comment by AP-NJA** [comment]
At the moment, you have to open the Creative menu for the sorting to work properly. From there, the sorting will work until you close the instance of Minecraft.

**Comment by Chailotl** [comment]
Fixed in a8df9d96d641f7c4817ef436a5f2205d9c28d87d
