### ISSUE TITLE
Unable to blacklist ComputerCraft screen

### ISSUE THREAD

**Issue by dragonmaus** [Chailotl/inventory-sort#14]
(Possibly related to #9 and/or #10.)

I am trying to blacklist the computer screens from the ComputerCraft mod ([CC: Tweaked](/cc-tweaked/CC-Tweaked), specifically), but not having any luck.

Blacklisting every "Screen" and "Handler" class[0] doesn't seem to work at all. The only class that actually removes the sort button from the middle of the computer screen is `dan200.computercraft.mixin.client.DebugScreenOverlayMixin`, but then Minecraft crashes whenever I try to open the normal inventory.

I asked about this on the ComputerCraft IRC, but the dev was perplexed as to why the `DebugScreenOverlayMixin` class worked at all, and suggested I ask here.

----

<details>
<summary>[0]</summary>
<br>
There are some unexpected classes here, but I was getting frustrated and so ended up grabbing every class that mentioned "Handler" or "Screen". 😅
<ul>
<li><code>dan200.computercraft.api.turtle.TurtleRefuelHandler</code>
<li><code>dan200.computercraft.client.gui.AbstractComputerScreen</code>
<li><code>dan200.computercraft.client.gui.ClientInputHandler</code>
<li><code>dan200.computercraft.client.gui.ComputerScreen</code>
<li><code>dan200.computercraft.client.gui.DiskDriveScreen</code>
<li><code>dan200.computercraft.client.gui.NoTermComputerScreen</code>
<li><code>dan200.computercraft.client.gui.OptionScreen</code>
<li><code>dan200.computercraft.client.gui.PrinterScreen</code>
<li><code>dan200.computercraft.client.gui.PrintoutScreen</code>
<li><code>dan200.computercraft.client.gui.TurtleScreen</code>
<li><code>dan200.computercraft.core.apis.http.request.HttpRequestHandler</code>
<li><code>dan200.computercraft.core.apis.http.websocket.WebsocketCompressionHandler</code>
<li><code>dan200.computercraft.core.apis.http.websocket.WebsocketHandler</code>
<li><code>dan200.computercraft.impl.TurtleRefuelHandlers</code>
<li><code>dan200.computercraft.shared.computer.core.InputHandler</code>
<li><code>dan200.computercraft.shared.computer.menu.ServerInputHandler</code>
<li><code>dan200.computercraft.shared.turtle.FurnaceRefuelHandler</code>
</ul>
</details>

**Comment by Chailotl** [comment]
Fixed in eaae859e0b25d60105867908466a033900745ab4
