### ISSUE TITLE
issue with sort options displaying on every "inventory" space (including modded)

### ISSUE THREAD

**Issue by taudjey** [Chailotl/inventory-sort#9]
it conflicts with my mods a lot; usually the buttons appear overlapping other stuff (and will be in the middle of/behind things), or the sort button will appear on a block that has a space that holds items and you'll be able to sort it, but then when you leave and come back to it, the block's inventory is all back to normal and unsorted.

i know that it's configurable which is good, so i just wanted to know if there's some lines i can put in the disabled/container screens config to universally disable all non-vanilla "inventory" spaces (i don't have any experience with configuring mod stuff so it's super hard trying to figure out how to fix this on my own lol T_T)

**Comment by Chailotl** [comment]
That's a good idea actually! I'll get to work on it asap
